# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a00527be39345d17cfc8b007a7b50ceabe313a347cd9bd661f771848e6ba24613e17696f7bb85bd389bf6f70a213de257e3c1f2346763341819754b5a5e020e

test:
  secret_key_base: d77422f6f0c9365f2fbfa7f7cbf9c778efcde5808842e95f0a4f6bf2b130d01dc1b5a5107178e3659419a630e5784464e95f37325b8486f30eaeb03d49bcb5ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
